# documentation: https://book.orthanc-server.com/users/docker.html
version: '3.6'
services:

  viewer:
    image: ohif/viewer:v4.9.8.14493
    container_name: viewer
    depends_on:
      - orthanc
    ports:
      - 80:80
    volumes:
      # Nginx as a reversed proxy for orthanc and the viewer
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # OHIF Viewer configuration to reach DICOMWeb endpoints
      - ./config/viewer.js:/usr/share/nginx/html/app-config.js:ro
      # university logo
      - ./config/assets/unia-logo.png:/usr/share/nginx/html/assets/unia-logo.png

  orthanc:
    image: jodogne/orthanc-plugins:1.9.7
    container_name: orthanc
    volumes:
      # persistent data
      - ./orthanc-db/:/var/lib/orthanc/db
      # config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
    command: /etc/orthanc/orthanc.json # Path to the configuration files 
    environment:
      - ORTHANC_NAME=PACS2go
      - DW_ENABLED=true
