version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: jodogne/orthanc:latest
    volumes:
      - ./tmp/orthanc-db/:/var/lib/orthanc/db/
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=PACS2go
secrets:
  orthanc.json:
    file: orthanc.json